# Generated by Django 5.0.6 on 2024-07-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favoriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedUser', models.CharField(max_length=255)),
                ('restaurant', models.CharField(max_length=255)),
            ],
        ),
    ]
