# Generated by Django 5.0.6 on 2024-06-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aff", "0002_restaurantlist"),
    ]

    operations = [
        migrations.RemoveField(model_name="resturant", name="address",),
        migrations.RemoveField(model_name="resturant", name="cuisine",),
        migrations.RemoveField(model_name="resturant", name="email",),
        migrations.RemoveField(model_name="resturant", name="name",),
        migrations.RemoveField(model_name="resturant", name="phone",),
        migrations.RemoveField(model_name="resturant", name="zipcode",),
    ]
